In [40]:
import tensorflow as tf
from tensorflow.keras import layers, losses

import numpy as np
import cv2

In [42]:
img = cv2.imread(r'/awlab/users/chsu/WorkSpace/tensorflow/segmentation/data/p2017017086_ki67_merge/images/CH_171219_Vh31_Goldilocks_plate_2017017086_ki67_G9_0000.png')
img.max()

255

In [56]:
conv_1x1 = layers.Conv2D(3, (1, 1), activation='softmax')

x = tf.random.normal([1, 3, 3, 10])
y_pred = conv_1x1(x)
y_true = tf.random.uniform([1, 3, 3], 0, 3, dtype=tf.int32)
y_true = tf.one_hot(y_true, 3)

print(y_pred)
print(y_true)

tf.Tensor(
[[[[0.5844983  0.21547134 0.20003042]
   [0.32524666 0.44815135 0.22660203]
   [0.41977277 0.3969772  0.18325005]]

  [[0.3008043  0.10755826 0.5916375 ]
   [0.1713046  0.14538315 0.6833123 ]
   [0.4155173  0.04341767 0.541065  ]]

  [[0.05367538 0.84446204 0.10186251]
   [0.3022408  0.5178963  0.17986292]
   [0.3306585  0.61141866 0.05792283]]]], shape=(1, 3, 3, 3), dtype=float32)
tf.Tensor(
[[[[0. 1. 0.]
   [1. 0. 0.]
   [0. 0. 1.]]

  [[0. 0. 1.]
   [0. 0. 1.]
   [0. 0. 1.]]

  [[0. 1. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(1, 3, 3, 3), dtype=float32)


In [57]:
# loss = losses.sparse_categorical_crossentropy(y_true, y_pred)
loss = losses.categorical_crossentropy(y_true, y_pred)
print(loss)

tf.Tensor(
[[[1.5349274  1.1231716  1.6969037 ]
  [0.52486116 0.3808033  0.6142158 ]
  [0.16905536 0.65798026 2.8486438 ]]], shape=(1, 3, 3), dtype=float32)


In [59]:
L = np.zeros_like(loss)

for i in range(L.shape[1]):
    for j in range(L.shape[2]):
#         c = tf.squeeze(y_true[0,i,j])
        c = y_true[0,i,j,:].numpy() == 1.
#         print(c)
        L[0,i,j] = -tf.math.log(y_pred.numpy()[0,i,j,c])
print(L)

[[[1.5349274  1.1231714  1.6969037 ]
  [0.52486116 0.3808033  0.6142159 ]
  [0.16905549 0.65798026 2.8486438 ]]]


In [60]:
L[:,:,1:]

array([[[1.1231714 , 1.6969037 ],
        [0.3808033 , 0.6142159 ],
        [0.65798026, 2.8486438 ]]], dtype=float32)